version: '3'

services:

  mysql-master:
    image: mysql:8.0
    container_name: "mysql-master"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    command:
      - --server-id=1
      - --default-authentication-plugin=mysql_native_password
      - --log-bin=mysql-bin
      - --binlog-format=ROW
      - --enforce-gtid-consistency=ON
      - --log-slave-updates=ON
      - --relay-log=mysql-relay-bin
      - --report-host=
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot" ]
      interval: 5s
      timeout: 5s
      retries: 10

  mysql-slave-one:
    image: mysql:8.0
    container_name: "mysql-slave-one"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: slave-one
      MYSQL_PASSWORD: slave
    command:
      - --server-id=2
      - --default-authentication-plugin=mysql_native_password
      - --log-bin=mysql-bin
      - --relay-log=mysql-relay-bin
    ports:
      - '3307:3306'
    depends_on:
      mysql-master:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot" ]
      interval: 5s
      timeout: 5s
      retries: 10

  mysql-slave-two:
    image: mysql:8.0
    container_name: "mysql-slave-two"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: slave-two
      MYSQL_PASSWORD: slave
    command:
      - --server-id=3
      - --default-authentication-plugin=mysql_native_password
      - --log-bin=mysql-bin
      - --relay-log=mysql-relay-bin
      - --read-only=ON
    ports:
      - '3308:3306'
    depends_on:
      mysql-master:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot" ]
      interval: 5s
      timeout: 5s
      retries: 10
